version: '3.7'

services:

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/docker/nginx/data:/data
      - /root/docker/nginx/letsencrypt:/etc/letsencrypt
    networks:
      mired:
        ipv4_address: 172.20.0.2
        
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '80:80/tcp'
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'Europe/Madrid'
    volumes:
      - /root/docker/etc-pihole:/etc/pihole
      - /root/docker/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped      

networks:
  mired:
    ipam:
      config:
        - subnet: 172.20.0.0/16
