version: '3.7'

services:

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      mired:
        ipv4_address: 172.20.0.2
      
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8180:80/tcp
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'chinarro'  
    volumes:
      - ./pihole/etc-pihole/:/etc/pihole/'
      - ./pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      mired:
        ipv4_address: 172.20.0.3

networks:
  mired:
    ipam:
      config:
        - subnet: 172.20.0.0/16
