version: '3.7'

services:

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/docker/nginx/data:/data
      - /root/docker/nginx/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.2
        
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8100:80/tcp'
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'chinarro'
    volumes:
      - /root/docker/pihole/etc-pihole:/etc/pihole
      - /root/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.3
 diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /root/docker/diun/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - 'TZ=Europe/Madrid'
      - 'LOG_LEVEL=info'
      - 'LOG_JSON=false'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=0 */6 * * *'
      - 'DIUN_WATCH_JITTER=30s'
      - 'DIUN_PROVIDERS_DOCKER=true'
    labels:
      - "diun.enable=true"
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.4
        
networks:
  mired:
    ipam:
      config:
        - subnet: 172.20.0.0/16
