version: '3.7'

services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      containers:
        ipv4_address: 172.20.0.2
      
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    expose:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8180:80/tcp"
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'chinarro'  
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.3

networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24
