version: '3.7'

services:

  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /root/docker/nginx/data:/data
      - /root/docker/nginx/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.2
        
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      - '8100:80/tcp'
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'chinarro'
    volumes:
      - /root/docker/pihole/etc-pihole:/etc/pihole
      - /root/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.3
  
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /root/docker/homer/assets/:/www/assets
    user: 0:0
    ports:
      - '8092:8080'
    restart: always
    networks:
      mired:
        ipv4_address: 172.20.0.4
        
networks:
  mired:
    ipam:
      config:
        - subnet: 172.20.0.0/16
